import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
// import styles from "./layout.css"
import "./globals.css";

const montserrat = Montserrat({ subsets: ["latin", "cyrillic"] });

export const metadata: Metadata = {
  title: "Eye's of buddha menu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <div className="main">{children}</div>
      </body>
    </html>
  );
}
